import { NextRequest, NextResponse } from 'next/server';

/**
 * Backup Submission API Route
 * Receives form data from HubSpot form submissions and sends backup emails via Resend
 * This ensures we never lose a lead even if HubSpot fails
 */

const RESEND_API_KEY = process.env.RESEND_API_KEY;
const TO_EMAIL = process.env.QUOTE_TO_EMAIL || 'inquiry@genetargeting.com';
const FROM_EMAIL = process.env.QUOTE_FROM_EMAIL || 'quotes@genetargeting.com';

interface BackupSubmissionData {
  formId: string;
  formName: string;
  pageUrl: string;
  submittedAt: string;
  fields: Record<string, string | string[]>;
}

export async function POST(request: NextRequest) {
  try {
    const data: BackupSubmissionData = await request.json();

    if (!data.formId || !data.fields) {
      return NextResponse.json(
        { error: 'Form ID and fields are required' },
        { status: 400 }
      );
    }

    // Format fields for email display
    const fieldRows = Object.entries(data.fields)
      .map(([key, value]) => {
        const displayValue = Array.isArray(value) ? value.join(', ') : value;
        return `<div class="field"><span class="label">${formatFieldName(key)}:</span> <span class="value">${displayValue || 'Not provided'}</span></div>`;
      })
      .join('');

    const fieldRowsText = Object.entries(data.fields)
      .map(([key, value]) => {
        const displayValue = Array.isArray(value) ? value.join(', ') : value;
        return `${formatFieldName(key)}: ${displayValue || 'Not provided'}`;
      })
      .join('\n');

    // Email HTML template
    const emailHtml = `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; line-height: 1.6; color: #333; }
    .container { max-width: 600px; margin: 0 auto; padding: 20px; }
    .header { background: linear-gradient(135deg, #dc2626 0%, #991b1b 100%); color: white; padding: 30px; text-align: center; }
    .header h1 { margin: 0; font-size: 24px; }
    .badge { display: inline-block; background: rgba(255,255,255,0.2); padding: 4px 12px; border-radius: 12px; font-size: 12px; margin-top: 8px; }
    .content { background: #f7f7f7; padding: 30px; }
    .alert { background: #fef2f2; border: 2px solid #dc2626; border-radius: 8px; padding: 16px; margin-bottom: 20px; }
    .alert-text { color: #991b1b; font-weight: 600; margin: 0; }
    .section { background: white; padding: 20px; margin-bottom: 20px; border-left: 4px solid #008080; }
    .section h2 { color: #0a253c; font-size: 16px; margin: 0 0 15px 0; text-transform: uppercase; letter-spacing: 1px; }
    .field { margin-bottom: 12px; }
    .label { font-weight: 600; color: #0a253c; display: inline-block; min-width: 180px; }
    .value { color: #333; }
    .footer { text-align: center; padding: 20px; color: #666; font-size: 12px; }
    .meta { background: #f0f9ff; padding: 15px; border-left: 4px solid #3b82f6; margin-bottom: 20px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <h1>🚨 Backup Form Submission</h1>
      <p style="margin: 10px 0 0 0; opacity: 0.9;">ingenious targeting laboratory</p>
      <span class="badge">REDUNDANCY BACKUP</span>
    </div>
    
    <div class="content">
      <div class="alert">
        <p class="alert-text">⚠️ This is a backup copy of a HubSpot form submission. The primary submission also went to HubSpot.</p>
      </div>

      <div class="meta">
        <h2 style="color: #1e40af; font-size: 14px; margin: 0 0 10px 0;">Submission Metadata</h2>
        <div class="field"><span class="label">Form Name:</span> <span class="value">${data.formName || 'Unknown Form'}</span></div>
        <div class="field"><span class="label">Form ID:</span> <span class="value">${data.formId}</span></div>
        <div class="field"><span class="label">Page URL:</span> <span class="value">${data.pageUrl || 'Not captured'}</span></div>
        <div class="field"><span class="label">Submitted At:</span> <span class="value">${data.submittedAt}</span></div>
      </div>
      
      <div class="section">
        <h2>Form Data</h2>
        ${fieldRows}
      </div>
    </div>
    
    <div class="footer">
      <p>This backup submission was automatically generated by the ITL website form monitoring system.</p>
      <p>Primary submission should already be in HubSpot CRM.</p>
    </div>
  </div>
</body>
</html>
    `;

    const emailText = `
BACKUP FORM SUBMISSION - ingenious targeting laboratory
======================================================
⚠️ This is a backup copy. Primary submission went to HubSpot.

METADATA
--------
Form Name: ${data.formName || 'Unknown Form'}
Form ID: ${data.formId}
Page URL: ${data.pageUrl || 'Not captured'}
Submitted At: ${data.submittedAt}

FORM DATA
---------
${fieldRowsText}

---
This backup was automatically generated by the ITL website form monitoring system.
    `;

    // Check if Resend API key is configured
    if (!RESEND_API_KEY) {
      console.log('RESEND_API_KEY not configured. Backup submission logged:', data);
      return NextResponse.json(
        { 
          success: true, 
          message: 'Backup logged (email not configured)',
          warning: 'RESEND_API_KEY not set'
        },
        { status: 200 }
      );
    }

    // Send backup email via Resend
    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to: [TO_EMAIL],
        subject: `🚨 BACKUP: ${data.formName || 'Form Submission'} - ${data.fields.email || data.fields.firstname || 'Lead'}`,
        html: emailHtml,
        text: emailText,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json();
      console.error('Resend API error:', errorData);
      return NextResponse.json(
        { error: 'Failed to send backup email', details: errorData },
        { status: 500 }
      );
    }

    const result = await response.json();
    
    return NextResponse.json(
      { success: true, message: 'Backup submission recorded', id: result.id },
      { status: 200 }
    );

  } catch (error) {
    console.error('Error processing backup submission:', error);
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    );
  }
}

/**
 * Format field names from HubSpot internal names to readable labels
 */
function formatFieldName(fieldName: string): string {
  const fieldMap: Record<string, string> = {
    firstname: 'First Name',
    lastname: 'Last Name',
    email: 'Email',
    phone: 'Phone',
    company: 'Company',
    jobtitle: 'Job Title',
    message: 'Message',
    gene_symbol: 'Gene Symbol',
    modification_type: 'Modification Type',
    model_type: 'Model Type',
    strain_background: 'Strain Background',
    timeline_requirements: 'Timeline Requirements',
    cohort_needs: 'Cohort Needs',
    additional_notes: 'Additional Notes',
    preferred_contact: 'Preferred Contact Method',
  };

  return fieldMap[fieldName] || fieldName
    .split('_')
    .map(word => word.charAt(0).toUpperCase() + word.slice(1))
    .join(' ');
}
