name: Lighthouse CI

on:
  workflow_dispatch:
  push:
    branches: [main, ITL_MAIN, ITL_DEV]

jobs:
  lhci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 20
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Run Lighthouse CI
        run: npm run lhci
